---
language: node_js
node_js:
- '0.10'
- '0.8'
notifications:
  campfire:
    - secure: 'fM8Rp08B+piNE9cMVNiwTKavoZRMb6ioRumUUI62nQY9jtgP1AzBuVVPQAxDjuoALaxvwEqOWciam9dAhXaQ1Jwvq9rBEqJTMV2x2RFZy+WVmWT9DUClcepilzvC+txig5vijlMGtLVdDPNNCoR5KROxrtcIb/O0A7gB3s5rM74='
